builds:
  - id: cli
    binary: "cli"
    dir: cmd/cli/
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
  - id: web
    binary: "web"
    dir: cmd/web/
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - builds:
      - cli
    format_overrides:
      - goos: windows
        format: zip
    files:
      - features/*
dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - web
    dockerfile: Dockerfile
    skip_push: auto
    image_templates:
      - "janoszen/fh-cloudcomputing-handin-automation"
    extra_files:
      - features
dist: build
release:
  github:
    owner: fh-cloud-computing
    name: hand-in-automation
  prerelease: auto
  extra_files:
    - glob: features/*
